server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: EA_Project

  datasource:
    url: jdbc:mysql://localhost:3306/fanfare_borcht?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Updates schema without dropping existing data
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true  # Show SQL queries in logs

  servlet:
    multipart:
      enabled: true           # Enable file uploads
      max-file-size: 5MB      # Maximum file size (adjust as needed)
      max-request-size: 10MB  # Maximum request size (adjust as needed)
      file-size-threshold: 2KB # File size threshold for temporary storage

spring.mvc.hiddenmethod.filter.enabled: true
